In [1]:
from preprocessing import *
from feature_extraction import extract_features
import cv2
import numpy as np
import glob
import joblib
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [2]:
arr = [0, 1, 2, 3, 4, 5]
data=[]
hog_features = []

In [3]:
# extract features from men dataset
for label in arr:
    dirList = glob.glob("../../Dataset_0-5/men/"+str(label)+"/*.jpg")    
    for img_path in dirList:
        try:
            # read the image
            im= cv2.imread(img_path)
            img = cv2.resize(im, (256,256))

            # pre-processing
            result_image=shadow_removalDialte(img)
            preprocessed_image=preprocessing(result_image,img)
            
            # feature extraction
            fd = extract_features(preprocessed_image)
            
            # append the label and the image to the dataset
            hog_features.append(fd)
            data.append(label)
        except:
            pass

In [4]:
# extract features from men dataset
for label in arr:
    dirList = glob.glob("../../Dataset_0-5/Women/"+str(label)+"/*.jpg")
    
    for img_path in dirList:
        try:
            # read the image
            im= cv2.imread(img_path)
            img = cv2.resize(im, (256,256))

            # pre-processing
            result_image=shadow_removalDialte(img)
            preprocessed_image=preprocessing(result_image,img)
            
            # feature extraction
            fd = extract_features(preprocessed_image)
            
            # append the label and the image to the dataset
            hog_features.append(fd)
            data.append(label)
        except:
            pass

In [5]:
# split the dataset into training and testing sets
train_x,test_x,train_y,test_y = train_test_split(hog_features,data, test_size = 0.2)
# train the model
classifier=SVC(kernel="poly", random_state=6)
classifier.fit(train_x,train_y)
# joblib.dump(classifier, "model/models3")

SVC(kernel='poly', random_state=6)

In [8]:
# predict the labels of the test set
prediction=classifier.predict(test_x)
# show the accuracy, precision, recall, f1-score, and confusion matrix
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.8489010989010989
Precision=  0.8567781606182128
Recall=  0.8489010989010989
F1 Score=  0.8510623307538547
Confusion Matrix=  [[59  0  0  1  0  0]
 [ 0 54  6  0  1  0]
 [ 0  1 51 12  4  0]
 [ 1  0  5 40 10  1]
 [ 0  0  0  4 44  3]
 [ 0  0  0  4  2 61]]
Classification Report=                precision    recall  f1-score   support

           0       0.98      0.98      0.98        60
           1       0.98      0.89      0.93        61
           2       0.82      0.75      0.78        68
           3       0.66      0.70      0.68        57
           4       0.72      0.86      0.79        51
           5       0.94      0.91      0.92        67

    accuracy                           0.85       364
   macro avg       0.85      0.85      0.85       364
weighted avg       0.86      0.85      0.85       364



In [6]:
from sklearn.ensemble import RandomForestClassifier

# Create a random forest classifier and fit it to the training data
rfc = RandomForestClassifier(n_estimators=150)
rfc.fit(train_x, train_y)
joblib.dump(rfc, "model/rfc_model")

['model/rfc_model']

In [7]:
prediction=rfc.predict(test_x)
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.7939560439560439
Precision=  0.7960629724365987
Recall=  0.7939560439560439
F1 Score=  0.7932069570462748
Confusion Matrix=  [[59  0  0  1  1  0]
 [ 0 52  5  0  0  0]
 [ 1  2 45  5  2  1]
 [ 5  1 11 40  9  3]
 [ 0  0  3  9 39  2]
 [ 0  1  2  8  3 54]]
Classification Report=                precision    recall  f1-score   support

           0       0.91      0.97      0.94        61
           1       0.93      0.91      0.92        57
           2       0.68      0.80      0.74        56
           3       0.63      0.58      0.61        69
           4       0.72      0.74      0.73        53
           5       0.90      0.79      0.84        68

    accuracy                           0.79       364
   macro avg       0.80      0.80      0.80       364
weighted avg       0.80      0.79      0.79       364



In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(train_x, train_y)
joblib.dump(knn, "model/knn_model.pkl")


['model/knn_model.pkl']

In [10]:
prediction=knn.predict(test_x)
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.7582417582417582
Precision=  0.7820666030144051
Recall=  0.7582417582417582
F1 Score=  0.7655166265378801
Confusion Matrix=  [[63  0  0  0  1  0]
 [ 0 55 16  2  0  0]
 [ 0  1 38 11  1  2]
 [ 2  0 10 30 13  2]
 [ 0  0  2 14 35  1]
 [ 0  0  0  6  4 55]]
Classification Report=                precision    recall  f1-score   support

           0       0.97      0.98      0.98        64
           1       0.98      0.75      0.85        73
           2       0.58      0.72      0.64        53
           3       0.48      0.53      0.50        57
           4       0.65      0.67      0.66        52
           5       0.92      0.85      0.88        65

    accuracy                           0.76       364
   macro avg       0.76      0.75      0.75       364
weighted avg       0.78      0.76      0.77       364



In [14]:
from sklearn.ensemble import AdaBoostClassifier

adab_clf = AdaBoostClassifier(random_state=42)
adab_clf.fit(train_x, train_y)

AdaBoostClassifier(random_state=42)

In [15]:
prediction=adab_clf.predict(test_x)
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.5357142857142857
Precision=  0.5263359591228444
Recall=  0.5357142857142857
F1 Score=  0.5218224617814501
Confusion Matrix=  [[36  0  2  1  1  0]
 [ 1 35  3  0  0  3]
 [12 15 30 20  7  9]
 [ 8  1 11 20 12  6]
 [ 2  0  7 15 35  8]
 [ 1  4  9  5  6 39]]
Classification Report=                precision    recall  f1-score   support

           0       0.60      0.90      0.72        40
           1       0.64      0.83      0.72        42
           2       0.48      0.32      0.39        93
           3       0.33      0.34      0.34        58
           4       0.57      0.52      0.55        67
           5       0.60      0.61      0.60        64

    accuracy                           0.54       364
   macro avg       0.54      0.59      0.55       364
weighted avg       0.53      0.54      0.52       364



In [11]:
import xgboost as xgb
# Train an XGBoost Classifier on the training set
dtrain = xgb.DMatrix(train_x, label=train_y)
dtest = xgb.DMatrix(test_x, label=test_y)

param = {'max_depth': 3, 'eta': 0.1, 'objective': 'multi:softmax', 'num_class': 6}
num_round = 10
bst = xgb.train(param, dtrain, num_round)
joblib.dump(rfc, "model/xgb_model.pkl")

['model/xgb_model.pkl']

In [12]:
prediction=bst.predict(dtest)
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.6620879120879121
Precision=  0.6669669768570868
Recall=  0.6620879120879121
F1 Score=  0.6621637912594661
Confusion Matrix=  [[53  2  2  2  1  1]
 [ 0 43  5  4  0  0]
 [ 4  5 30 10  5  0]
 [ 7  2 21 30  9  3]
 [ 1  2  3 12 33  4]
 [ 0  2  5  5  6 52]]
Classification Report=                precision    recall  f1-score   support

         0.0       0.82      0.87      0.84        61
         1.0       0.77      0.83      0.80        52
         2.0       0.45      0.56      0.50        54
         3.0       0.48      0.42      0.44        72
         4.0       0.61      0.60      0.61        55
         5.0       0.87      0.74      0.80        70

    accuracy                           0.66       364
   macro avg       0.67      0.67      0.66       364
weighted avg       0.67      0.66      0.66       364

