In [1]:
from preprocessing import *
from feature_extraction import extract_features
import cv2
import numpy as np
import glob
import joblib
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [2]:
arr = [0, 1, 2, 3, 4, 5]
data=[]
hog_features = []

In [3]:
# extract features from men dataset
for label in arr:
    dirList = glob.glob("../../Dataset_0-5/men/"+str(label)+"/*.jpg")    
    for img_path in dirList:
        try:
            # read the image
            im= cv2.imread(img_path)
            img = cv2.resize(im, (256,256))

            # pre-processing
            result_image=shadow_removalDialate(img)
            preprocessed_image=preprocessing(result_image,img)
            
            # feature extraction
            fd = extract_features(preprocessed_image)
            
            # append the label and the image to the dataset
            hog_features.append(fd)
            data.append(label)
        except:
            pass

In [6]:
# extract features from men dataset
for label in arr:
    dirList = glob.glob("../../Dataset_0-5/Women/"+str(label)+"/*.jpg")
    
    for img_path in dirList:
        try:
            # read the image
            im= cv2.imread(img_path)
            img = cv2.resize(im, (256,256))

            # pre-processing
            result_image=shadow_removalDialate(img)
            preprocessed_image=preprocessing(result_image,img)
            
            # feature extraction
            fd = extract_features(preprocessed_image)
            
            # append the label and the image to the dataset
            hog_features.append(fd)
            data.append(label)
        except:
            pass

In [7]:
# split the dataset into training and testing sets
train_x,test_x,train_y,test_y = train_test_split(hog_features,data, test_size = 0.2)
# train the model
classifier=SVC(kernel="poly", random_state=6)
classifier.fit(train_x,train_y)
# joblib.dump(classifier, "model/models3")

SVC(kernel='poly', random_state=6)

In [8]:
# predict the labels of the test set
prediction=classifier.predict(test_x)
# show the accuracy, precision, recall, f1-score, and confusion matrix
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.8489010989010989
Precision=  0.8567781606182128
Recall=  0.8489010989010989
F1 Score=  0.8510623307538547
Confusion Matrix=  [[59  0  0  1  0  0]
 [ 0 54  6  0  1  0]
 [ 0  1 51 12  4  0]
 [ 1  0  5 40 10  1]
 [ 0  0  0  4 44  3]
 [ 0  0  0  4  2 61]]
Classification Report=                precision    recall  f1-score   support

           0       0.98      0.98      0.98        60
           1       0.98      0.89      0.93        61
           2       0.82      0.75      0.78        68
           3       0.66      0.70      0.68        57
           4       0.72      0.86      0.79        51
           5       0.94      0.91      0.92        67

    accuracy                           0.85       364
   macro avg       0.85      0.85      0.85       364
weighted avg       0.86      0.85      0.85       364



In [9]:
from sklearn.ensemble import RandomForestClassifier

# Create a random forest classifier and fit it to the training data
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(train_x, train_y)

RandomForestClassifier(n_estimators=200)

In [10]:
prediction=rfc.predict(test_x)
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.8131868131868132
Precision=  0.82923628291057
Recall=  0.8131868131868132
F1 Score=  0.8170535571489385
Confusion Matrix=  [[55  0  0  1  2  0]
 [ 1 53  4  0  1  0]
 [ 3  1 52  5  4  0]
 [ 0  1  4 44 17  3]
 [ 0  0  0  5 33  3]
 [ 1  0  2  6  4 59]]
Classification Report=                precision    recall  f1-score   support

           0       0.92      0.95      0.93        58
           1       0.96      0.90      0.93        59
           2       0.84      0.80      0.82        65
           3       0.72      0.64      0.68        69
           4       0.54      0.80      0.65        41
           5       0.91      0.82      0.86        72

    accuracy                           0.81       364
   macro avg       0.81      0.82      0.81       364
weighted avg       0.83      0.81      0.82       364



In [12]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(train_x, train_y)

KNeighborsClassifier(n_neighbors=9)

In [13]:
prediction=knn.predict(test_x)
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.8021978021978022
Precision=  0.8153139196970299
Recall=  0.8021978021978022
F1 Score=  0.8049158260629272
Confusion Matrix=  [[60  0  0  0  1  0]
 [ 0 54 10  1  1  0]
 [ 0  1 40  4  1  0]
 [ 0  0 10 39 15  2]
 [ 0  0  1 12 40  4]
 [ 0  0  1  5  3 59]]
Classification Report=                precision    recall  f1-score   support

           0       1.00      0.98      0.99        61
           1       0.98      0.82      0.89        66
           2       0.65      0.87      0.74        46
           3       0.64      0.59      0.61        66
           4       0.66      0.70      0.68        57
           5       0.91      0.87      0.89        68

    accuracy                           0.80       364
   macro avg       0.80      0.81      0.80       364
weighted avg       0.82      0.80      0.80       364



In [14]:
from sklearn.ensemble import AdaBoostClassifier

adab_clf = AdaBoostClassifier(random_state=42)
adab_clf.fit(train_x, train_y)

AdaBoostClassifier(random_state=42)

In [15]:
prediction=adab_clf.predict(test_x)
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.5357142857142857
Precision=  0.5263359591228444
Recall=  0.5357142857142857
F1 Score=  0.5218224617814501
Confusion Matrix=  [[36  0  2  1  1  0]
 [ 1 35  3  0  0  3]
 [12 15 30 20  7  9]
 [ 8  1 11 20 12  6]
 [ 2  0  7 15 35  8]
 [ 1  4  9  5  6 39]]
Classification Report=                precision    recall  f1-score   support

           0       0.60      0.90      0.72        40
           1       0.64      0.83      0.72        42
           2       0.48      0.32      0.39        93
           3       0.33      0.34      0.34        58
           4       0.57      0.52      0.55        67
           5       0.60      0.61      0.60        64

    accuracy                           0.54       364
   macro avg       0.54      0.59      0.55       364
weighted avg       0.53      0.54      0.52       364



In [16]:
import xgboost as xgb
# Train an XGBoost Classifier on the training set
dtrain = xgb.DMatrix(train_x, label=train_y)
dtest = xgb.DMatrix(test_x, label=test_y)

param = {'max_depth': 3, 'eta': 0.1, 'objective': 'multi:softmax', 'num_class': 6}
num_round = 10
bst = xgb.train(param, dtrain, num_round)

In [17]:
prediction=bst.predict(dtest)
print("Accuracy= ",metrics.accuracy_score(prediction, test_y))
print("Precision= ",metrics.precision_score(prediction, test_y, average='weighted'))
print("Recall= ",metrics.recall_score(prediction, test_y, average='weighted'))
print("F1 Score= ",metrics.f1_score(prediction, test_y, average='weighted'))
print("Confusion Matrix= ",metrics.confusion_matrix(prediction, test_y))
print("Classification Report= ",metrics.classification_report(prediction, test_y))

Accuracy=  0.6868131868131868
Precision=  0.6923647824331224
Recall=  0.6868131868131868
F1 Score=  0.6842543744300438
Confusion Matrix=  [[46  0  0  1  2  2]
 [ 4 42  5  0  0  2]
 [ 3  6 37  7  2  0]
 [ 6  1 14 38 20  2]
 [ 1  0  2 10 32  4]
 [ 0  6  4  5  5 55]]
Classification Report=                precision    recall  f1-score   support

         0.0       0.77      0.90      0.83        51
         1.0       0.76      0.79      0.78        53
         2.0       0.60      0.67      0.63        55
         3.0       0.62      0.47      0.54        81
         4.0       0.52      0.65      0.58        49
         5.0       0.85      0.73      0.79        75

    accuracy                           0.69       364
   macro avg       0.69      0.70      0.69       364
weighted avg       0.69      0.69      0.68       364

